In [1]:
import pandas  as pd
import numpy as np

#Read the training data and testing data
training_data = pd.read_excel(r'Titanic_Survival_train.xls', index_col=0,header=0)
testing_data = pd.read_excel(r'Titanic_Survival_test.xls',index_col=0,header=0)
print(training_data.shape)
print(testing_data.shape)

(891, 11)
(21, 11)


In [2]:
training_data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [3]:
testing_data.head()

Survived  Pclass  \
PassengerId                     
871                 0       3   
872                 1       1   
873                 0       1   
874                 0       3   
875                 1       2   

                                                         Name     Sex   Age  \
PassengerId                                                                   
871                                         Balkic, Mr. Cerin    male  26.0   
872          Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0   
873                                  Carlsson, Mr. Frans Olof    male  33.0   
874                               Vander Cruyssen, Mr. Victor    male  47.0   
875                     Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0   

             SibSp  Parch     Ticket     Fare        Cabin Embarked  
PassengerId                                                          
871              0      0     349248   7.8958          NaN        S  
872              1      1      11751  52.5542          D35        S  
873              0      0        695   5.0000  B51 B53 B55        S  
874              0      0     345765   9.0000          NaN        S  
875              1      0  P/PP 3381  24.0000          NaN        C

In [4]:
#feature selection 
training_data = training_data[['Name','Pclass','Sex','Age','Survived']]
testing_data = testing_data[['Name','Pclass','Sex','Age','Survived']]
print(training_data.shape)
print(testing_data.shape)

(891, 5)
(21, 5)


In [5]:
#finding the missing values
print(training_data.isnull().sum())
print(testing_data.isnull().sum())

Name          0
Pclass        0
Sex           0
Age         177
Survived      0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         2
Survived    0
dtype: int64


In [6]:
#imputing numerical missing data with mean value

training_data["Age"].fillna(int(training_data["Age"].mean()),inplace=True)
print(training_data.isnull().sum())
#imputing numerical missing data with mean value

testing_data["Age"].fillna(int(testing_data["Age"].mean()),inplace=True)
print(testing_data.isnull().sum())

Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64
Name        0
Pclass      0
Sex         0
Age         0
Survived    0
dtype: int64


In [7]:
print(training_data.loc[:871,["Age"]].mean())
print(training_data["Age"].mean())

Age    29.551286
dtype: float64
29.56023569023569


In [8]:
#transforming categorical data to numerical

from sklearn import preprocessing

colname=['Sex']

le=preprocessing.LabelEncoder()

for x in colname:
    training_data[x]=le.fit_transform(training_data[x])
    testing_data[x]=le.fit_transform(testing_data[x])
    
#training_data["Sex"]=training_data["Sex"].map({"female":0,"male":1})
#testing_data["Sex"]=testing_data["Sex"].map({"female":0,"male":1})


In [9]:
print(training_data.head())

print(testing_data.head())

                                                          Name  Pclass  Sex  \
PassengerId                                                                   
1                                      Braund, Mr. Owen Harris       3    1   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...       1    0   
3                                       Heikkinen, Miss. Laina       3    0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)       1    0   
5                                     Allen, Mr. William Henry       3    1   

              Age  Survived  
PassengerId                  
1            22.0         0  
2            38.0         1  
3            26.0         1  
4            35.0         1  
5            35.0         0  
                                                         Name  Pclass  Sex  \
PassengerId                                                                  
871                                         Balkic, Mr. Cerin       3    1   
87

In [10]:
training_data.iloc[869,:]

Name        Johnson, Master. Harold Theodor
Pclass                                    3
Sex                                       1
Age                                       4
Survived                                  1
Name: 870, dtype: object

In [11]:
X_train=training_data.values[:870,1:-1]
Y_train=training_data.values[:870,-1]
Y_train=Y_train.astype(int)

X_test=testing_data.values[:,1:-1]
Y_test=testing_data.values[:,-1]
Y_test=Y_test.astype(int)

In [12]:
X_train.shape

(870, 3)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test=scaler.transform(X_test)
#while working on separate train and test data, fit the scaler object only upon the train data 
#and use the same scaler object to transform both the train as well as the test data.

In [15]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))), 
                               metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 0), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 0), (0, 0)]


In [14]:
import numpy as np
np.sqrt(len(X_train))

29.49576240750525

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
print()

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[14  0]
 [ 2  5]]

Classification report: 
              precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       1.00      0.71      0.83         7

    accuracy                           0.90        21
   macro avg       0.94      0.86      0.88        21
weighted avg       0.92      0.90      0.90        21

Accuracy of the model:  0.9047619047619048


In [17]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)



Accuracy is  0.8095238095238095 for K-Value: 1
Accuracy is  0.8095238095238095 for K-Value: 2
Accuracy is  0.8095238095238095 for K-Value: 3
Accuracy is  0.8095238095238095 for K-Value: 4
Accuracy is  0.8571428571428571 for K-Value: 5
Accuracy is  0.8571428571428571 for K-Value: 6
Accuracy is  0.8571428571428571 for K-Value: 7
Accuracy is  0.9047619047619048 for K-Value: 8
Accuracy is  0.8571428571428571 for K-Value: 9
Accuracy is  0.8571428571428571 for K-Value: 10
Accuracy is  0.8571428571428571 for K-Value: 11
Accuracy is  0.9047619047619048 for K-Value: 12
Accuracy is  0.9047619047619048 for K-Value: 13
Accuracy is  0.9523809523809523 for K-Value: 14
Accuracy is  0.9047619047619048 for K-Value: 15
Accuracy is  0.9047619047619048 for K-Value: 16
Accuracy is  0.8095238095238095 for K-Value: 17
Accuracy is  0.8095238095238095 for K-Value: 18
Accuracy is  0.8571428571428571 for K-Value: 19
Accuracy is  0.8571428571428571 for K-Value: 20
Accuracy is  0.8571428571428571 for K-Value: 21
A

In [18]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

14 : 0.9523809523809523
22 : 0.9523809523809523


In [23]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=14, metric='manhattan')
#euclidean, manhattan,minkowski
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 1), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 0), (1, 1), (0, 0)]


In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

confusion_matrix=confusion_matrix(Y_test,Y_pred)
print(confusion_matrix)
print()
print("Classification report: ")

print(classification_report(Y_test,Y_pred))

accuracy_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",accuracy_score)

[[13  1]
 [ 0  7]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.88      1.00      0.93         7

    accuracy                           0.95        21
   macro avg       0.94      0.96      0.95        21
weighted avg       0.96      0.95      0.95        21

Accuracy of the model:  0.9523809523809523


In [25]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(0, 0), (1, 1), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 0), (0, 0), (1, 1), (1, 1), (0, 0), (0, 1), (0, 0), (0, 0), (0, 0), (0, 0), (1, 1), (0, 1), (1, 1), (0, 0)]


In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

confusion_matrix=confusion_matrix(Y_test,Y_pred)
print(confusion_matrix)
print()
print("Classification report: ")

print(classification_report(Y_test,Y_pred))

accuracy_score=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",accuracy_score)

[[12  2]
 [ 0  7]]

Classification report: 
              precision    recall  f1-score   support

           0       1.00      0.86      0.92        14
           1       0.78      1.00      0.88         7

    accuracy                           0.90        21
   macro avg       0.89      0.93      0.90        21
weighted avg       0.93      0.90      0.91        21

Accuracy of the model:  0.9047619047619048


In [ ]:
testing_data["Y_pred"]=Y_pred
testing_data


# Regression using KNN

In [27]:
# read data into a DataFrame
data = pd.read_csv(r'Advertising.csv', index_col=0,header=0)
data.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [28]:
data.isnull().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [29]:
# create X and y
X = data[['TV', 'radio', 'newspaper']]
Y = data['sales']

In [30]:
from sklearn.model_selection import train_test_split
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,
                                                    random_state=10)  

In [35]:
#predicting using the KNeighbors_Regressor
from sklearn.neighbors import KNeighborsRegressor
model_KNN=KNeighborsRegressor(n_neighbors=3, metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)
Y_pred=model_KNN.predict(X_test)

In [31]:
int(np.sqrt(len(X_train)))

12

In [36]:
from sklearn.metrics import r2_score,mean_squared_error
r2score=r2_score(Y_test,Y_pred)
print(r2score)
rmse=np.sqrt(mean_squared_error(Y_test,Y_pred))
print(rmse)

"""
Using Linear Regression:
RSquare=0.8348
RMSE=2.59

"""

0.9411330460488659
1.5478569414229182


'\nUsing Linear Regression:\nRSquare=0.8348\nRMSE=2.59\n\n'

In [34]:
from sklearn.metrics import r2_score

for K in range(1,16):
    model_KNN = KNeighborsRegressor(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("R-square is ", r2_score(Y_test,Y_pred), "for K-Value:",K)

R-square is  0.947505618529669 for K-Value: 1
R-square is  0.9293159406535845 for K-Value: 2
R-square is  0.9411330460488659 for K-Value: 3
R-square is  0.9394530965066451 for K-Value: 4
R-square is  0.9284857726620428 for K-Value: 5
R-square is  0.9171381300471962 for K-Value: 6
R-square is  0.8986986579101233 for K-Value: 7
R-square is  0.8941504138170911 for K-Value: 8
R-square is  0.8798578264845459 for K-Value: 9
R-square is  0.8608042002876257 for K-Value: 10
R-square is  0.8470466691144289 for K-Value: 11
R-square is  0.8483613805522731 for K-Value: 12
R-square is  0.8510763597780449 for K-Value: 13
R-square is  0.8490397921317565 for K-Value: 14
R-square is  0.8496233693296317 for K-Value: 15
